package defi

import (
	"context"
	"errors"
	"fmt"

	"github.com/ethereum/go-ethereum/accounts/abi/bind"
	"github.com/ethereum/go-ethereum/core/types"
	"github.com/tn606024/defi-simplify/client/account/simple7702"
	"github.com/tn606024/defi-simplify/client/contract"
	"github.com/tn606024/defi-simplify/config"
)

// ErrExecutionAccountMismatch is returned when a Flow is built for an account other than the transaction signer.
var ErrExecutionAccountMismatch = errors.New("flow account does not match transaction signer")

// ExecutionMode describes user-facing execution semantics.
type ExecutionMode string

const (
	// ExecutionEOA executes a one-call Flow as a normal EOA transaction.
	ExecutionEOA ExecutionMode = "eoa"
	// ExecutionAtomicEOA executes a Flow atomically through a delegated EOA.
	ExecutionAtomicEOA ExecutionMode = "atomic_eoa"
)

// Runner executes Flows using user-facing execution modes.
type Runner struct {
	conn  EthereumClient
	opts  *bind.TransactOpts
	chain config.Chain
}

// NewRunner creates a Flow runner for a chain and transaction signer.
func NewRunner(conn EthereumClient, opts *bind.TransactOpts, chain config.Chain) *Runner {
	return &Runner{
		conn:  conn,
		opts:  opts,
		chain: chain,
	}
}

// Execute builds and executes flow using mode.
func (r *Runner) Execute(ctx context.Context, flow *Flow, mode ExecutionMode) (*types.Receipt, error) {
	plan, executor, err := r.prepareExecution(ctx, flow, mode)
	if err != nil {
		return nil, err
	}
	return executor.ExecuteCalls(ctx, plan.Calls())
}

// ExecuteWithResult builds and executes flow, then validates the mined receipt
// against expectations generated by the same Flow steps.
//
// Failures before a receipt exists return a nil result. Once a receipt exists,
// transaction and semantic validation failures return both the partial result
// and an error so callers retain the transaction hash and decoded progress.
func (r *Runner) ExecuteWithResult(ctx context.Context, flow *Flow, mode ExecutionMode) (*ExecutionResult, error) {
	plan, executor, err := r.prepareExecution(ctx, flow, mode)
	if err != nil {
		return nil, err
	}
	if err := validateSemanticExecutionPlan(plan); err != nil {
		return nil, &ExecutionError{Stage: ExecutionStageValidation, Err: err}
	}
	receipt, err := executor.ExecuteCalls(ctx, plan.Calls())
	if receipt == nil {
		if err != nil {
			return nil, &ExecutionError{Stage: ExecutionStageTransaction, Err: err}
		}
		return nil, &ExecutionError{
			Stage: ExecutionStageTransaction,
			Err:   fmt.Errorf("%w: executor returned no receipt", ErrInvalidExecutionReceipt),
		}
	}
	if err != nil {
		return newExecutionResult(plan, receipt, SkipExecutionFailed), &ExecutionError{
			Stage: ExecutionStageTransaction,
			Err:   err,
		}
	}
	return ValidateExecution(plan, receipt)
}

func (r *Runner) prepareExecution(ctx context.Context, flow *Flow, mode ExecutionMode) (*ExecutionPlan, CallExecutor, error) {
	if r == nil {
		return nil, nil, errors.New("runner is nil")
	}
	if flow != nil && r.opts != nil && flow.account != r.opts.From {
		return nil, nil, fmt.Errorf("%w: flow account %s, signer %s", ErrExecutionAccountMismatch, flow.account.Hex(), r.opts.From.Hex())
	}

	var executor CallExecutor
	switch mode {
	case ExecutionEOA:
		executor = contract.NewDirectExecutor(r.conn, r.opts)
	case ExecutionAtomicEOA:
		implementation, err := r.chain.Simple7702AccountImplementationAddress()
		if err != nil {
			return nil, nil, fmt.Errorf("resolve Simple7702Account implementation: %w", err)
		}
		executor = simple7702.NewExecutor(r.conn, r.opts, implementation)
	default:
		return nil, nil, fmt.Errorf("unsupported execution mode %q", mode)
	}

	plan, err := flow.Build(ctx, r.conn)
	if err != nil {
		return nil, nil, err
	}
	return plan, executor, nil
}
