// Package catalogcodegen renders reviewed manifest entries as chain-package
// named references.
package catalogcodegen

import (
	"bytes"
	"errors"
	"fmt"
	"go/format"
	gotoken "go/token"
	"sort"

	"github.com/tn606024/defi-simplify/internal/assetmanifest"
)

// ErrInvalidInput identifies an asset list that cannot safely become a Go API.
var ErrInvalidInput = errors.New("invalid catalog code generation input")

// Generate renders deterministic Go declarations for every reviewed manifest
// asset. The generated variables remain reviewable in the same pull request as
// the manifest update.
func Generate(packageName string, manifestAssets []assetmanifest.Asset) ([]byte, error) {
	if !gotoken.IsIdentifier(packageName) {
		return nil, fmt.Errorf("%w: package name %q is not a Go identifier", ErrInvalidInput, packageName)
	}
	if len(manifestAssets) == 0 {
		return nil, fmt.Errorf("%w: asset list is empty", ErrInvalidInput)
	}

	assets := append([]assetmanifest.Asset(nil), manifestAssets...)
	sort.Slice(assets, func(i, j int) bool { return assets[i].ID < assets[j].ID })
	for i, asset := range assets {
		if !gotoken.IsIdentifier(asset.ID) {
			return nil, fmt.Errorf("%w: catalog ID %q is not a Go identifier", ErrInvalidInput, asset.ID)
		}
		if i > 0 && asset.ID == assets[i-1].ID {
			return nil, fmt.Errorf("%w: duplicate catalog ID %q", ErrInvalidInput, asset.ID)
		}
	}

	var source bytes.Buffer
	source.WriteString("// Code generated by update-aave-manifest; DO NOT EDIT.\n\n")
	fmt.Fprintf(&source, "package %s\n\n", packageName)
	source.WriteString("var (\n")
	for _, asset := range assets {
		fmt.Fprintf(
			&source,
			"\t// %s identifies the reviewed %s token contract in this catalog.\n\t%s = mustLookup(%q)\n",
			asset.ID,
			asset.ID,
			asset.ID,
			asset.ID,
		)
	}
	source.WriteString(")\n")

	formatted, err := format.Source(source.Bytes())
	if err != nil {
		return nil, fmt.Errorf("format generated catalog source: %w", err)
	}
	return formatted, nil
}
