package catalogcodegen

import (
	"errors"
	"strings"
	"testing"

	"github.com/tn606024/defi-simplify/internal/assetmanifest"
)

func TestGenerate(t *testing.T) {
	assets := []assetmanifest.Asset{
		{ID: "WETH"},
		{ID: "USDC"},
	}

	first, err := Generate("base", assets)
	if err != nil {
		t.Fatalf("Generate() error = %v", err)
	}
	second, err := Generate("base", assets)
	if err != nil {
		t.Fatalf("Generate() second error = %v", err)
	}
	if string(first) != string(second) {
		t.Fatal("repeated generation produced different bytes")
	}
	wantOrder := "USDC = mustLookup(\"USDC\")"
	wethOrder := "WETH = mustLookup(\"WETH\")"
	if strings.Index(string(first), wantOrder) >= strings.Index(string(first), wethOrder) {
		t.Fatalf("generated declarations are not sorted\n%s", first)
	}
	if !strings.HasPrefix(string(first), "// Code generated by update-aave-manifest; DO NOT EDIT.\n") {
		t.Fatalf("generated source is missing the generated-code header\n%s", first)
	}
}

func TestGenerateRejectsInvalidInput(t *testing.T) {
	tests := []struct {
		name        string
		packageName string
		assets      []assetmanifest.Asset
	}{
		{name: "invalid package", packageName: "base-chain", assets: []assetmanifest.Asset{{ID: "USDC"}}},
		{name: "empty assets", packageName: "base"},
		{name: "invalid identifier", packageName: "base", assets: []assetmanifest.Asset{{ID: "USDC.E"}}},
		{name: "duplicate identifier", packageName: "base", assets: []assetmanifest.Asset{{ID: "USDC"}, {ID: "USDC"}}},
	}

	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			_, err := Generate(test.packageName, test.assets)
			if !errors.Is(err, ErrInvalidInput) {
				t.Fatalf("Generate() error = %v, want ErrInvalidInput", err)
			}
		})
	}
}
