// Code generated by update-aave-manifest; DO NOT EDIT.

package base

var (
	// AAVE identifies the reviewed AAVE token contract in this catalog.
	AAVE = mustLookup("AAVE")
	// CBBTC identifies the reviewed CBBTC token contract in this catalog.
	CBBTC = mustLookup("CBBTC")
	// CBETH identifies the reviewed CBETH token contract in this catalog.
	CBETH = mustLookup("CBETH")
	// EURC identifies the reviewed EURC token contract in this catalog.
	EURC = mustLookup("EURC")
	// EZETH identifies the reviewed EZETH token contract in this catalog.
	EZETH = mustLookup("EZETH")
	// GHO identifies the reviewed GHO token contract in this catalog.
	GHO = mustLookup("GHO")
	// LBTC identifies the reviewed LBTC token contract in this catalog.
	LBTC = mustLookup("LBTC")
	// SYRUPUSDC identifies the reviewed SYRUPUSDC token contract in this catalog.
	SYRUPUSDC = mustLookup("SYRUPUSDC")
	// TBTC identifies the reviewed TBTC token contract in this catalog.
	TBTC = mustLookup("TBTC")
	// USDBC identifies the reviewed USDBC token contract in this catalog.
	USDBC = mustLookup("USDBC")
	// USDC identifies the reviewed USDC token contract in this catalog.
	USDC = mustLookup("USDC")
	// WEETH identifies the reviewed WEETH token contract in this catalog.
	WEETH = mustLookup("WEETH")
	// WETH identifies the reviewed WETH token contract in this catalog.
	WETH = mustLookup("WETH")
	// WRSETH identifies the reviewed WRSETH token contract in this catalog.
	WRSETH = mustLookup("WRSETH")
	// WSTETH identifies the reviewed WSTETH token contract in this catalog.
	WSTETH = mustLookup("WSTETH")
)
